## Write a Numpy program to compute the multiplication of two given matrixes

In [1]:
import numpy as np



In [2]:
a = [[1,2,3],[4,5,6]]
b=[[7,8,9],[10,11,12]]
np.multiply(a,b)

array([[ 7, 16, 27],
       [40, 55, 72]])

## Write a NumPy program to compute the determinant of a given square array

In [7]:
x=np.array([[10,20],[30,40]])
np.linalg.det(x)


-200.0000000000001

## Write a NumPy program to compute the cross product of two given vectors

In [8]:
a=[10,20,30]
b=[40,50,60]
np.cross(a,b)

array([-300,  600, -300])

## Write a NumPy program to compute the condition number of a given matrix

In [10]:
x=np.array([[10,20],[30,40]])
np.linalg.norm(x)*np.linalg.norm(np.linalg.inv(x))

14.999999999999996

In [12]:
np.linalg.cond(x, p='fro')

14.999999999999996

## Write a NumPy program to compute the inverse of a given matrix

In [13]:
z=[[10,20,30],[40,50,60],[70,80,90]]


In [14]:

np.linalg.inv(z)

array([[ 7.03687442e+13, -1.40737488e+14,  7.03687442e+13],
       [-1.40737488e+14,  2.81474977e+14, -1.40737488e+14],
       [ 7.03687442e+13, -1.40737488e+14,  7.03687442e+13]])