In [3]:
a=[[1,2,3],[4,5,6]]
b=[[7,8,9],[10,11,12]]

def mul_wise(x,y):
    assert len(x)==len(y)
    return [x_i * y_i for x_i,y_i in zip(x,y)]

def mul_element_wise(a,b):
    c=[]
    for i in range(len(a)):
        c.append(mul_wise(a[i],b[i]))
    return c

print(mul_element_wise(a,b))

[[7, 16, 27], [40, 55, 72]]


In [13]:


def mul2ele(x,y):
    len(x)==len(y)
    return sum([x_i * y_i for x_i , y_i in zip(x,y)])

def mul_element_wise(a,b):
    c=[]
    for i in range(len(a)):
        c.append(mul2ele(a[i],b))
        #becouse it will multible matrix with 1*2 to matrix of 3*3
    return c



a=[[1,2,3],[4,5,6]]
b=[7,10]
print(mul_element_wise(a,b))

[27, 78]


In [27]:
def mulexp(x,y):
    
    return [x * y_i for  y_i in y]

def number_on_it(b,s):
    c=[]
    for i in range(len(b)):
        c.append(mulexp(b[i] , s))
    return c

s=4
b=[[12,13],[15,14],[15,16]]
print(number_on_it(b,s))

TypeError: 'int' object is not iterable

In [33]:
my_list=[1,2,3]
type(my_list)

list

In [ ]:
#numerical paython 

In [34]:
import numpy as np

In [36]:
np.array(my_list)

array([1, 2, 3])

In [38]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

x=np.array(my_matrix)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
x.shape
#return shape of matrix of numpy

(3, 3)

In [42]:
np.arange(0,10)
#range from 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(0,150,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148])

In [46]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [49]:
np.zeros((5,5))
#matrix of zeros  note you have two brackets

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [55]:
np.ones((25,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 

In [56]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [58]:
np.linspace(0,10,50)
#is a function neet مسطرة اقسمها حتت متساوية بمقدار كام حتة

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [59]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
#ارقام بين ال0و 1 uniform disturbution

np.random.rand(3)

array([0.81876398, 0.60076004, 0.21109328])

In [61]:
np.random.rand(5,10)

array([[0.1110955 , 0.70864898, 0.18052979, 0.04516758, 0.11423426,
        0.74539753, 0.64559724, 0.78206868, 0.87297224, 0.45220391],
       [0.82747567, 0.47394374, 0.0607389 , 0.5639312 , 0.71433483,
        0.3202795 , 0.90812582, 0.42444314, 0.94033091, 0.62041938],
       [0.37083306, 0.81187438, 0.95267465, 0.83753624, 0.43042575,
        0.04010141, 0.1307167 , 0.08508945, 0.23424467, 0.91058199],
       [0.65661597, 0.40162997, 0.52472902, 0.40148456, 0.30680546,
        0.16528858, 0.43412061, 0.848429  , 0.13484806, 0.89972146],
       [0.36283918, 0.53569293, 0.09666691, 0.63065167, 0.03089774,
        0.81652607, 0.9115469 , 0.42964793, 0.16239438, 0.27020837]])

In [63]:
np.random.randn(2)
#standard normal disturb from -3.5:+1.5

array([0.94961188, 0.30733381])

In [66]:
np.random.randn(5,5)

array([[ 0.12724355,  0.71181248,  0.32172964,  1.52069764,  0.09298099],
       [-0.76238947,  0.63329076,  1.7628764 ,  1.19917597,  0.63510368],
       [-0.86483194, -0.5604357 ,  0.22228121, -2.12741456,  1.93972889],
       [ 3.02243581, -1.60856708, -0.48416699, -0.42954004,  0.63069564],
       [ 0.56160845,  0.24611365, -1.67393019,  0.40373528, -0.17090372]])

In [70]:
np.random.randint(4,100)
#integer random number

31

In [73]:
np.random.randint(4,100,15)
#15 numbers froom 4:100
#task make a matrix from rand int
np.random.randint(4,100,(3,3))

array([[83, 61, 12],
       [94, 68, 79],
       [93, 71, 49]])

In [77]:
arr=np.arange(25)
ranarr=np.random.randint(0,50,10)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [79]:
ranarr

array([26, 23, 30, 31,  0, 15,  3, 28, 45,  6])

In [80]:
arr.reshape(5,5)
#thats mean reshape the array that we made before note that reshape must be = array of shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [83]:
ranarr.max()

45

In [84]:
ranarr.argmax()
#location of maximum number

8

In [87]:
ranarr.min()

0

In [89]:
ranarr.argmin()
#location of minimum number

4

In [95]:
arro2=np.arange(10,22)

In [96]:
arro2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [98]:
arro2[5]

15

In [100]:
arro2[1:5]

array([11, 12, 13, 14])

In [102]:
arro2[0:5]
# indexing of normal array

array([10, 11, 12, 13, 14])

In [104]:
arro2[0:5] = 100


In [105]:
arro2
#replace number fixed in a slice of array =prot casting 

array([100, 100, 100, 100, 100,  15,  16,  17,  18,  19,  20,  21])

In [112]:
#nutability =ability to change
arro2=np.arange(10,22)

In [113]:
arro2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [110]:
slice_of_array=arro2[0:6]

slice_of_array[:]=99
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [114]:
arr_copy=arro2.copy()
arr_copy

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [116]:
arr_2d=np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [120]:
arr_2d[0:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [122]:
arr_2d[:2,0:]
#عاوز من الاول لحد رو 2 ومن الاخر من صفر للاخر
#اول صفين بس كل العواميد بالمعني

array([[ 5, 10, 15],
       [20, 25, 30]])

In [126]:
arr_2d < 10
#look like filter condidional

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [127]:
bool_arr = arr_2d < 10
bool_arr

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [131]:
arr+arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [132]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [133]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])

In [134]:
arr/arr
#nan=infinitr number    =1/0

C:\Users\PC\AppData\Local\Temp\ipykernel_11284\1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [135]:
1/arr

C:\Users\PC\AppData\Local\Temp\ipykernel_11284\255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158,
       0.05      , 0.04761905, 0.04545455, 0.04347826, 0.04166667])

In [136]:
arr**5

array([      0,       1,      32,     243,    1024,    3125,    7776,
         16807,   32768,   59049,  100000,  161051,  248832,  371293,
        537824,  759375, 1048576, 1419857, 1889568, 2476099, 3200000,
       4084101, 5153632, 6436343, 7962624], dtype=int32)

In [137]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [138]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10])

In [139]:
np.max(arr)

24

In [140]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836])

In [142]:
np.log(arr)

C:\Users\PC\AppData\Local\Temp\ipykernel_11284\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383])

In [143]:
#glassclor
#payscope

In [145]:
#coloum axis=0
#row axis=1
#panda is obsite of them

In [ ]:
m=np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])